# Generated by Django 5.1.1 on 2024-10-07 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_student_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student_register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('standard', models.CharField(max_length=10)),
                ('contact_number', models.CharField(max_length=15)),
                ('parent_email', models.EmailField(max_length=254)),
            ],
        ),
    ]
