# Generated by Django 5.1.1 on 2024-10-07 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_student_register'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student_register',
        ),
        migrations.AlterField(
            model_name='student',
            name='password',
            field=models.CharField(max_length=128),
        ),
    ]
