# Generated by Django 5.1.1 on 2024-10-08 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_delete_login_delete_student_register_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('tagline', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('greetings', models.CharField(max_length=255)),
                ('prompt', models.CharField(max_length=2000)),
                ('subject', models.CharField(max_length=100)),
            ],
        ),
    ]
