# Generated by Django 5.1.1 on 2024-10-08 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_pdfembedding'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pdfembedding',
            name='uploaded_at',
        ),
    ]
