# Generated by Django 5.1.1 on 2024-10-08 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_remove_pdfembedding_uploaded_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="teacher",
            name="id",
            field=models.AutoField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="teacher",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
