# Generated by Django 5.1.1 on 2024-10-10 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0012_pdfembedding_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pdfembedding",
            name="user",
        ),
    ]
