# Generated by Django 5.1.1 on 2024-10-10 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0013_remove_pdfembedding_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pdfembedding",
            name="file",
        ),
        migrations.AddField(
            model_name="pdfembedding",
            name="file_name",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
    ]
